### PR TITLE
Making tags idempotent

### PR DESCRIPTION
**Pull request by jeffersongirao**
- Making tags idempotent (only that diff between existing and new tags are created/updated/deleted). 
- Making get_tags work when the tags exist under domain or/and project (querying just by id does not work in such context)

### CODE REVIEW

**Comment by jeffersongirao** [comment]
Hello @resmo, thanks for merging the another PR. Do you have any feedback on this one? Thanks!

**Comment by resmo** [comment]
@jeffersongirao, will look at it

**Comment by resmo** [comment]
LGTM. thanks for this.

**Comment by jeffersongirao** [comment]
Thank you, I'm working on the changes for the cs_instance we discussed by e-mail, I'm sending a PR soon. Please, feel free to merge the cs_volume into the ansible repo since you have the tooling in place already. Regards!

**Pull request merged**
