### PR TITLE
Add an option to allow the resize of root disk when the instance is c…

### PR DESCRIPTION
**Pull request by milamberspace**
…reated.

(need CloudStack 4.4 or +, cloud-initramfs-growroot installed on the template)

### CODE REVIEW

**Comment by resmo** [comment]
:+1: 
Do you like to update the official unreleased ansible module https://github.com/ansible/ansible-modules-extras/blob/devel/cloud/cloudstack/cs_instance.py as well or should I take over?

**Comment by milamberspace** [comment]
As you like. I saw only after my PR that they have the ansible-modules-extras project.
If I understand, the best way for the newt PR is: clone the ansible-module-extras and make the PR or continue with your ansible-cloudstack project?

**Comment by resmo** [comment]
"they" are me :). These modules will go into ansible 2.0. I keep them in sync as long as ansible 2.0 is not released. They are 100% compatible.

New PR on ansible-module-extras with your changes and I will be notified to give my :+1:

**Comment by milamberspace** [comment]
Work done for ansible module extras
https://github.com/ansible/ansible-modules-extras/pull/825

**Pull request merged**
