### PR TITLE
Feature/vpc

### LINKED ISSUE #41: VPC support in the wild
@resmo VPC support seen in the wild at:
https://github.com/SafeSwissCloud/ansible-cloudstack-vpc/blob/master/patches/cs_ip_address.py

### PR DESCRIPTION
**Pull request by resmo**
scratch down vpc support from https://github.com/SafeSwissCloud/ansible-cloudstack-vpc/issues/1 closes  #41

Thanks @runseb  @SafeSwissCloud
/cc @SafeSwissCloud

### CODE REVIEW

**Comment by FaKod** [comment]
Hi @resmo, so we'll see this VPC patch in Ansible 2.2?

**Comment by resmo** [comment]
yes. it is already in.

**Comment by resmo** [comment]
in 2.2

**Comment by FaKod** [comment]
perfect, thanks

**Pull request merged**
